/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package currency;

import javax.swing.JOptionPane;

/**
 *
 * @author ZNR
 */
public class Currency_Convert extends javax.swing.JFrame {

    /**
     * Creates new form Currency_Convert
     */
    public Currency_Convert() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_type = new javax.swing.JLabel();
        lbl_rate = new javax.swing.JLabel();
        lbl_amount = new javax.swing.JLabel();
        lbl_finalamount = new javax.swing.JLabel();
        lbl_famount = new javax.swing.JLabel();
        txt_amount = new javax.swing.JTextField();
        combox_type = new javax.swing.JComboBox<>();
        btn_convert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_type.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lbl_type.setText("Type");

        lbl_rate.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N

        lbl_amount.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lbl_amount.setText("Amount");

        lbl_finalamount.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lbl_finalamount.setText("Final Amount");

        lbl_famount.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N

        txt_amount.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txt_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_amountActionPerformed(evt);
            }
        });
        txt_amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_amountKeyReleased(evt);
            }
        });

        combox_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "USD", "AUD", "YEN", "GBP", "EUR" }));
        combox_type.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combox_typeItemStateChanged(evt);
            }
        });

        btn_convert.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btn_convert.setText("Convert");
        btn_convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_convertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_convert, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_finalamount, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_type, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_famount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_rate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_amount, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                            .addComponent(combox_type, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(31, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_type, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combox_type, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_convert, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(lbl_rate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_finalamount, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_famount, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_amountActionPerformed

    private void txt_amountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_amountKeyReleased
        if (!txt_amount.getText().isEmpty() ){
            if (!Character.isAlphabetic(evt.getKeyChar())) {
                
            } else {
                String s = txt_amount.getText();
                s = s.substring(0,s.length()-1);
                txt_amount.setText(s);
            }
            
        }
    }//GEN-LAST:event_txt_amountKeyReleased

    private void combox_typeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combox_typeItemStateChanged
        if (combox_type.getSelectedItem().toString().equals("USD")) {
            lbl_rate.setText("153.68");
        } else if (combox_type.getSelectedItem().toString().equals("Select"))  {
            lbl_rate.setText("0.00");
        }else if (combox_type.getSelectedItem().toString().equals("AUD"))  {
            lbl_rate.setText("120.15");
        }else if (combox_type.getSelectedItem().toString().equals("YEN"))  {
            lbl_rate.setText("1.37");
        }else if (combox_type.getSelectedItem().toString().equals("GBP"))  {
            lbl_rate.setText("207.76");
        }else if (combox_type.getSelectedItem().toString().equals("EUR"))  {
            lbl_rate.setText("183.29");
        }
    }//GEN-LAST:event_combox_typeItemStateChanged

    private void btn_convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_convertActionPerformed
        if (txt_amount.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,"Please enter the Amount!", "Message Box", JOptionPane.INFORMATION_MESSAGE);
        
        }else if (combox_type.getSelectedItem().toString().equals("Select")){
            JOptionPane.showMessageDialog(this,"Please select the currency type!", "Message Box", JOptionPane.INFORMATION_MESSAGE);
        
        } else {   
            double num1 = Double.valueOf(txt_amount.getText());
            double num2 = Double.valueOf(lbl_rate.getText());
            double ans = num1 * num2;
            lbl_famount.setText(String.valueOf(ans));
        }    
    }//GEN-LAST:event_btn_convertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Currency_Convert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Currency_Convert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Currency_Convert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Currency_Convert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Currency_Convert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_convert;
    private javax.swing.JComboBox<String> combox_type;
    private javax.swing.JLabel lbl_amount;
    private javax.swing.JLabel lbl_famount;
    private javax.swing.JLabel lbl_finalamount;
    private javax.swing.JLabel lbl_rate;
    private javax.swing.JLabel lbl_type;
    private javax.swing.JTextField txt_amount;
    // End of variables declaration//GEN-END:variables
}
